# version: "3.8"

# services:
#   basic_container:
#     build: .
#     image: sanky0709/sanket:v2
#     container_name: basic_container
#     ports:
#       - "5000:5000"
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_RUN_HOST=0.0.0.0
#       - FLASK_RUN_PORT=5000
#       - FLASK_DEBUG=1
#     command: flask run
#     restart: always




version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    container_name: sanket_api
    environment:
      - DB_PATH=/data/students.db
    volumes:
      - ./data:/data
    depends_on:
      - migrate

  migrate:
    image: python:3.10-slim
    volumes:
      - ./migrations:/migrations
      - ./data:/data
    working_dir: /migrations
    entrypoint: ["sh", "-c", "apt-get update && apt-get install -y sqlite3 && sqlite3 /data/students.db < init.sql"]
